export enum ReportCode {
  /* ---------- Guest Reports ---------- */
  GUEST_DAILY_SUMMARY = 'GUEST_DAILY_SUMMARY',
  GUEST_WEEKLY_SUMMARY = 'GUEST_WEEKLY_SUMMARY',
  GUEST_MONTHLY_SUMMARY = 'GUEST_MONTHLY_SUMMARY',
  GUEST_CATEGORY_ANALYSIS = 'GUEST_CATEGORY_ANALYSIS',

  /* ---------- Room Reports ----------- */
  ROOM_OCCUPANCY_TRENDS = 'ROOM_OCCUPANCY_TRENDS',
  ROOM_UTILIZATION = 'ROOM_UTILIZATION',
  HOUSEKEEPING_PERFORMANCE = 'HOUSEKEEPING_PERFORMANCE',

  /* ---------- Vehicle Reports -------- */
  VEHICLE_USAGE = 'VEHICLE_USAGE',
  DRIVER_PERFORMANCE = 'DRIVER_PERFORMANCE',
  FUEL_MAINTENANCE = 'FUEL_MAINTENANCE',

  /* ---------- Staff Reports ---------- */
  DUTY_PERFORMANCE = 'DUTY_PERFORMANCE',
  STAFF_RESPONSE_TIME = 'STAFF_RESPONSE_TIME',
  DEPARTMENT_WORKLOAD = 'DEPARTMENT_WORKLOAD',

  /* ---------- Notification ----------- */
  NOTIFICATION_LOGS = 'NOTIFICATION_LOGS',
  COMMUNICATION_ANALYTICS = 'COMMUNICATION_ANALYTICS',

  /* ---------- Food Reports ---------- */
  FOOD_SERVICE_UTILIZATION = 'FOOD_SERVICE_UTILIZATION',
}
