export enum ReportCode {
  /* ---------- Guest Reports ---------- */
  GUEST_DAILY_SUMMARY = 'GUEST_DAILY_SUMMARY',
  GUEST_WEEKLY_SUMMARY = 'GUEST_WEEKLY_SUMMARY',
  GUEST_MONTHLY_SUMMARY = 'GUEST_MONTHLY_SUMMARY',
  GUEST_CATEGORY_ANALYSIS = 'GUEST_CATEGORY_ANALYSIS',

  /* ---------- Room Reports ----------- */
  ROOM_DAILY_SUMMARY = 'ROOM_DAILY_SUMMARY',
  ROOM_WEEKLY_SUMMARY = 'ROOM_WEEKLY_SUMMARY',
  ROOM_MONTHLY_SUMMARY = 'ROOM_MONTHLY_SUMMARY',

  /* ---------- Vehicle Reports -------- */
  VEHICLE_DRIVER_DAILY_SUMMARY = 'VEHICLE_DAILY_SUMMARY',
  VEHICLE_DRIVER_WEEKLY_SUMMARY = 'VEHICLE_WEEKLY_SUMMARY',
  VEHICLE_DRIVER_MONTHLY_SUMMARY = 'VEHICLE_MONTHLY_SUMMARY',

  /* ---------- Driver Reports -------- */
  DRIVER_DAILY_SUMMARY = 'DRIVER_DAILY_SUMMARY',
  DRIVER_WEEKLY_SUMMARY = 'DRIVER_WEEKLY_SUMMARY',
  DRIVER_MONTHLY_SUMMARY = 'DRIVER_MONTHLY_SUMMARY',

  /* ---------- Driver Reports ---------- */
  DRIVER_DUTY_DAILY_SUMMARY = 'DRIVER_DUTY_DAILY_SUMMARY',
  DRIVER_DUTY_WEEKLY_SUMMARY = 'DRIVER_DUTY_WEEKLY_SUMMARY',
  DRIVER_DUTY_MONTHLY_SUMMARY = 'DRIVER_DUTY_MONTHLY_SUMMARY',

  /* ---------- Food Reports ---------- */
  FOOD_SERVICE_DAILY_SUMMARY = 'FOOD_SERVICE_DAILY_SUMMARY',
  FOOD_SERVICE_WEEKLY_SUMMARY = 'FOOD_SERVICE_WEEKLY_SUMMARY',
  FOOD_SERVICE_MONTHLY_SUMMARY = 'FOOD_SERVICE_MONTHLY_SUMMARY',

  /* ---------- Network Reports ---------- */
  NETWORK_DAILY_SUMMARY = 'NETWORK_DAILY_SUMMARY',
  NETWORK_WEEKLY_SUMMARY = 'NETWORK_WEEKLY_SUMMARY',
  NETWORK_MONTHLY_SUMMARY = 'NETWORK_MONTHLY_SUMMARY',
}
